name: Production workflow

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup mode
              uses: actions/setup-node@v3
            - name: Install dependencies
              run: npm install
            - name: Formatting and linting
              run: |
                  npm run format
                  npm run lint
            - name: Tests
              run: npm run test
